Lesson3
AlexSura/Thinknetica_Rails pull request #3
Opened 2023-01-23 09:08 UTC by AlexSura

не смог сделать 3 задание, не понимаю почему не объединяет таблицы

2023-01-23 16:59 UTC, BubuntuClu requested changes

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/category.rb
> +     has_many :tests
отступы поплыли

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/category.rb
> +     has_many :categories, through: :tests
зачем категории уметь находить категории? в чем смысл этой ассоциации?

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/test.rb
> +    testt = Test.joins('JOIN categories ON tests.category_id = categories.id')
ты знаком с операцией `join`, надо ее использовать тут, чтобы за один запрос получить данные

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/test.rb
> +    cat = Category.where("title == ?", string)
так писать нельзя. это очень уязвимый код для взлома. еще рано конечно про это, но посмотри про sql-injection. используй синтаксис рубишный `where(title: string)`, в нем заложена защита от склинъекций

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :tests, through: :users
тут таже ситуация как и с категорией. кажется, ты не совсем понял как работает эта ассоциация. лучше удалить, урок по ассоциациям слудующий

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.list(string)
задавай понятные имена методам и переменным. сейчас не понятно чего ожидать от твоего кода. лист, а лист чего? что за строку в нее подаем?

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/test.rb
> +    testt = testt.where("categories.id == ?", id_categories)
так не принято в рубях писать(в данном случае). без переприсваивания давай запишем, каждый вызов метода в отдельной строке

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :users, through: :tests
аналогично

2023-01-23 16:59 UTC, BubuntuClu commented on app/models/user.rb
> +    pp Test.where("level == ?", integer)
тоже самое замечание про склинекцию.
и тут у тебя никак не задействован пользователь. нужно найти все тесты по прохождениям пользователя. для этого тебе надо реализовать связь многие-ко-многим

2023-01-23 16:59 UTC, BubuntuClu commented on db/migrate/20230114170026_create_tests.rb
> +class CreateTests < ActiveRecord::Migration[6.1]
вообще этих файлом у тебя не должно было быть. ты не смержил прошлый ПР. в одно время у тебя должен быть активный только один ПР.
давай тогда так, прошлый ПР закрой, в рамках этого ПРа будем правки вносить в миграции. почему-то ты не исправил замечания по миграциям.

2023-01-23 16:59 UTC, BubuntuClu commented on db/migrate/20230114170026_create_tests.rb
> +    change_column_default(:tests, :level, from:nil, to: false)
этого кода не должно быть. у тебя в каждой миграции должен быть только блок `craete_table`. все остальное задается через опции к колонкам. во всех миграциях это надо поправить

2023-01-23 16:59 UTC, BubuntuClu commented on db/seeds.rb
> +tests = Test.create([{title: 'PHP', level: 1, category_id: 1}, {title: 'JS', level: 1, category_id: 1}, {title: 'React', level: 2, category_id: 2}])
1 - ты создаешь тесты, до того как создаешь категории. а как это будет работать? у тебя ведь тест привязывается к категории.
2 - у тебя в ID везде указана конкретная цифра, так нельзя делать; у тебя может не быть объекта с таким id в момент выполнения сида и данные тогда не будут созданы. тебе нужно использовать объекты, которые ты создаешь и их подставлять в выражения создания дочерних объектов. и из них брать `id` значения

2023-01-25 16:44 UTC, BubuntuClu commented on app/models/test.rb
> +    testt = Test.joins("JOIN categories ON tests.category_id = categories.id WHERE categories.title = '#{name_category}'")
```
Test.joins("JOIN categories ON tests.category_id = categories.id WHERE categories.title = '#{name_category}'")
  .order(title: :desc)
  .pluck("title")
```

6 и 7 строка в твоем коде не будут склаыдваться. в результате ты получешь не сортированный массив

2023-01-25 16:44 UTC, BubuntuClu commented on app/models/user.rb
> +    name_test = Test.joins("JOIN users ON users.id = tests.id WHERE tests.level = '#{level}'")
переменная тут не нужна

2023-01-25 16:46 UTC, BubuntuClu requested changes

2023-01-25 16:46 UTC, BubuntuClu commented on db/seeds.rb
> +tests = Test.create([{title: 'PHP', level: 1, category_id: 1}, {title: 'JS', level: 1, category_id: 1}, {title: 'React', level: 2, category_id: 2}])
тут не исправил хардкод айдишников

2023-01-25 16:46 UTC, BubuntuClu commented on db/migrate/20230114170026_create_tests.rb
> +    change_column_default(:tests, :level, from:nil, to: false)
миграции не исправил

2023-01-25 16:46 UTC, BubuntuClu commented on app/models/user.rb
> +    name_test = Test.joins("JOIN users ON users.id = tests.id WHERE tests.level = '#{level}'")
нельзя связать таблицу тестов и пользователей по id. это разные `id`, они не сопоставимы

2023-01-27 17:59 UTC, BubuntuClu commented on app/models/test.rb
> +    testt = Test.joins("JOIN categories ON tests.category_id = categories.id WHERE categories.title = '#{name_category}'")
не исправил

2023-01-27 17:59 UTC, BubuntuClu commented on db/seeds.rb
> +Test.create([{title: 'PHP', level: 1, category_id: nil}, {title: 'JS', level: 1, category_id: nil }, {title: 'React', level: 2, category_id:nil }])
тебе надо указывать `id` для создания объектов

вот допустим ты создал категории `categories = Category.create([{title: 'junior'},{title: 'midle'}])`

далее для создания теста, тебе надо указать к какой категории его привязать. у тебя есть массив только что созданных категорий и ты можешь получить их `id`
`tests = Test.create([{title: 'PHP', level: 1, category_id: categories[0].id}, {title: 'JS', level: 1, category_id: categories[0].id}, {title: 'React', level: 2, category_id: categories[1].id}])`

так же надо поступить и с остальными строками ниже

2023-01-27 17:59 UTC, BubuntuClu commented on app/models/user.rb
> +    name_test = self.tests.where(level: level)
по заданию тебе надо вернуть тесты, а не заголовки, поэтому можно просто 
```
def history(level)
    tests.where(level: level)
end
```

2023-01-28 09:51 UTC, AlexSura commented on db/seeds.rb
> +Test.create([{title: 'PHP', level: 1, category_id: nil}, {title: 'JS', level: 1, category_id: nil }, {title: 'React', level: 2, category_id:nil }])
не совсем понимаю про что речь идет

2023-01-28 17:52 UTC, BubuntuClu requested changes

2023-01-28 17:52 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "answers_id"
этот столбец не нужен в таблице вопросов. у тебя ответы привязываются к вопросам

2023-01-28 17:52 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "questions_id"
и этот тоже лишний. вопросы привязываются к тестам за счет наличия в таблице колонки `test_id`.

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230127051419_create_join_table_tests_users.rb
> +      t.integer :test_id
это должны быть внешние ключи

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170212_create_categories.rb
> +    create_table :categories do |t|
таблица тестов создается раньше таблицы категорий, и уже при создании тестов идет обращение во внешнем ключе к табилце категорий, которой еще не существует. в Бд типа постгре это уже не будет работать и ты получишь ошибку. надо поменять порядок миграций

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170151_create_users.rb
> +      #указать внешний ключ к категориям
это не надо ничего указывать

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170151_create_users.rb
> +    #change_column_null(:users, :name, :age, false)
ненужгый код удали из миграций

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/sadfaf.rb
> +Test: model
что это за файл? кажется какой-то мусор

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170120_create_answers.rb
> +      t.integer :question_id
этот столбец лишний, ты в операции `t.references` создаешь связь с таблицей вопросов

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170120_create_answers.rb
> +      t.reference :questions, :answers, foreign_key: true
неправильный синтаксис. `t.reference :qeustion, foreing_key: true` - так будет правильно. таблица для связи в единственном числе и не надо указывать какую таблицу связать, так как ты вблоке этой таблицы находишься

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170047_create_questions.rb
> +      t.integer :test_id
тоже самое что и в ответах

2023-01-28 17:52 UTC, BubuntuClu commented on db/migrate/20230114170026_create_tests.rb
> +      t.integer :category_id
тоже самое что и в ответах

2023-01-28 17:53 UTC, BubuntuClu commented on db/seeds.rb
> +Test.create([{title: 'PHP', level: 1, category_id: nil}, {title: 'JS', level: 1, category_id: nil }, {title: 'React', level: 2, category_id:nil }])
у тебя в таблице тестов есть столбец `category_id`. ты его сейчас не заполняешь, а он нужен чтобы понимать к какой категории привязан тест. значение для столбца надо получать динамически

2023-01-28 17:53 UTC, BubuntuClu commented on db/seeds.rb
> +Test.create([{title: 'PHP', level: 1, category_id: nil}, {title: 'JS', level: 1, category_id: nil }, {title: 'React', level: 2, category_id: nil}])
https://github.com/AlexSura/Thinknetica_Rails/pull/3#discussion_r1089782381

2023-01-28 19:43 UTC, AlexSura commented on db/migrate/sadfaf.rb
> +Test: model
да я тоже его увидел, происхождение его мне не известно

2023-02-01 15:57 UTC, merged