lesson4
AlexSura/Thinknetica_Rails pull request #4
Opened 2023-02-01 16:04 UTC by AlexSura

2023-02-01 16:54 UTC, BubuntuClu requested changes

2023-02-01 16:54 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
имя ассоциации дублируется. одна из них не будет рабоать

2023-02-01 16:54 UTC, BubuntuClu commented on app/models/user.rb
> +  def autor
это должна быть ассоциация, а не метод

2023-02-01 16:54 UTC, BubuntuClu commented on db/migrate/20230114170026_create_tests.rb
> +      t.integer :user_id
нельзя править миграции, которые уже смержены, надо откатить все изменения в миграциях и создать новые миграции с требуемым кодом. и тут должен быть внешний ключ

2023-02-01 16:54 UTC, BubuntuClu commented on db/migrate/20230114170151_create_users.rb
> +      t.integer :test_id
зачем этот столбец? за что он отвечает?

2023-02-03 17:35 UTC, BubuntuClu requested changes

2023-02-03 17:35 UTC, BubuntuClu commented on app/models/question.rb
> +  has_one :answer
ответ может иметь несколько ответов - тут будет `has_many`

2023-02-03 17:35 UTC, BubuntuClu commented on db/migrate/20230202083705_add_authorship_to_tests_users.rb
> +    add_column :tests_users, :authorship_id, :boolean
ты добавил столбец, а как он в приложении используется для авторства? ты не указал ассоциации авторства.

по сути авторство никак не отличается от того что у тебя тест принадлежит категории. тест принадлежит автору. тебе надо повторить эту свзяь только между таблицами пользователя и тестами.

2023-02-07 05:33 UTC, VidgarVii requested changes

2023-02-07 05:33 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
если вопрос удалить, то в текущем варианте можно в дальнейшем получить ошибку
к примеру при попытке обратиться по ассоциации (`@test.question`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления вопроса в таблице `answers` останется в поле `question_id` ссылка на несуществующий объект
т.е. объекты в таблице `answers` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `question_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `questions` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "questions" violates foreign key constraint
```
и рельсы откажутся удалять этот вопрос

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2023-02-07 05:33 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2023-02-07 05:33 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
нет ассоциации с категорией

2023-02-07 05:33 UTC, VidgarVii commented on app/models/test.rb
>      testt = Test.joins("JOIN categories ON tests.category_id = categories.id WHERE categories.title = '#{name_category}'")
1. Не стоит писать оператор WHERE внутри JOIN. Это разные логические операции.
2. с использованием ассоциации `joins` можно сильно сократить

2023-02-07 05:33 UTC, VidgarVii commented on db/seeds.rb
>  tests = Test.create([{title: 'PHP', level: 1, category_id: categories[0].id}, {title: 'JS', level: 1, category_id: categories[0].id }, {title: 'React', level: 2, category_id: categories[1].id}])
теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2023-02-08 13:32 UTC, VidgarVii requested changes

2023-02-08 13:32 UTC, VidgarVii commented on db/migrate/20230114170026_create_tests.rb
> +      t.references :category, foreign_key: true
тест обязательно должен принадлежать какой-нибудь категории. По этому стоит добавить null false

2023-02-08 13:32 UTC, VidgarVii commented on db/migrate/20230206121553_add_author_to_tests.rb
> +    add_reference :tests, :author_id, foreign_key: true
не верно использован метод add_reference.
Смотри документацию
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2023-03-22 17:41 UTC, BubuntuClu requested changes

2023-03-22 17:41 UTC, BubuntuClu commented on app/models/test.rb
>      testt = Test.joins("JOIN categories ON tests.category_id = categories.id WHERE categories.title = '#{name_category}'")
это не поправил. разбей на два метода `joins` и `where`. в `joins` попроубй использовать ассоциацию категорий, которую ты добавил выше в файле

2023-03-22 17:41 UTC, BubuntuClu commented on db/migrate/20230114170151_create_users.rb
> +      t.integer :test_id
не ответил

2023-03-22 17:41 UTC, BubuntuClu commented on app/models/question.rb
> +  has_many :answers
тут разумный комментарий, раз о нем упомянули стоит поправить. обычно до этого доходят чуть позже

2023-03-24 18:27 UTC, BubuntuClu requested changes

2023-03-24 18:27 UTC, BubuntuClu commented on app/models/test.rb
> +    x = "#{name_category}"
это лишнее действие. в формате записи `(category: { title: x })` интерполяцию вставлять не надо

2023-03-24 18:27 UTC, BubuntuClu commented on app/models/test.rb
> +    testt = Test.all.joins(:category).where(category: { title: x }).order(title: :desc)
`.all` тут лишнее

2023-04-19 07:05 UTC, merged